version: "3.7"
services:
  sir-lancebot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sir-lancebot
    init: true

    restart: always
    depends_on:
      - redis

    environment:
      - BOT_TOKEN
      - BOT_DEBUG
      - BOT_GUILD
      - BOT_ADMIN_ROLE_ID
      - CHANNEL_DEVLOG
      - CHANNEL_COMMUNITY_BOT_COMMANDS
      - REDIS_HOST=redis

    volumes:
      - .:/bot

  redis:
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"
