blank_issues_enabled: false
contact_links:
  - name: Python Discord Community
    url: https://discord.gg/python
    about: Contributors must be part of the community, so be sure to join!
  - name: Contributing Guide
    url: https://pythondiscord.com/pages/contributing/sir-lancebot/
